name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  bootstrap:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest

    name: bootstrap
    runs-on: ${{ matrix.os }}
    steps:
      - name: install neovim nightly
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-20.04" ]; then
            suffix=linux64
          else
            suffix=macos
          fi
          curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim-${suffix}.tar.gz | sudo tar -C /usr/local --strip 1 -xzf -

      - name: install deps on mac
        if: matrix.os == 'macos-latest'
        run: |
          brew install bash shellcheck ninja libyaml elixir opam

      - name: install deps on ubuntu
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck ninja-build libyaml-dev opam

      - uses: actions/checkout@v2.3.4

      - run: make shellcheck

      - name: get opam version
        id: get-opam-version
        run: |
          echo "::set-output name=version::$(opam --version)"
        shell: bash

      - name: opam cache
        id: opam-cache
        uses: actions/cache@v2.1.3
        with:
          path: ~/.opam
          key: "${{ matrix.os }}-${{ steps.get-opam-version.outputs.version }}"

      - name: opam init
        run: opam init --disable-sandboxing -n

      - uses: actions/setup-node@v2.1.4
        with:
          node-version: "14.x"

      - uses: actions/setup-python@v2.1.4
        with:
          python-version: "3.x"

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable

      - uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.x"

      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: "master"

      - name: copy files to config dir
        run: |
          mkdir -p $HOME/.config
          cp -rv $PWD $HOME/.config/nvim

      - name: langservers cache
        id: nvim-langservers-cache
        uses: actions/cache@v2.1.3
        with:
          path: ~/.cache/nvim/langservers
          key: "${{ matrix.os }}-${{ hashFiles('langservers/setup.sh') }}"

      - name: bootstrap from config dir
        env:
          NVIM_DEBUG: 1
        run: |
          eval "$(opam env)"
          make -j -f $HOME/.config/nvim/Makefile bootstrap

      - name: run luacheck from config dir
        run: make -f $HOME/.config/nvim/Makefile luacheck
